# The URL the site will be built for
base_url = "https://xecarlox94.github.io/"

title = "My Website"
description = "Personal Website"

default_language = "en"

compile_sass = true

build_search_index = true

output_dir = "docs"

generate_sitemap = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
