# The URL the site will be built for
base_url = "https://xecarlox94.github.io/"

title = "My Website"
description = "Personal Website"

default_language = "en"

compile_sass = true

build_search_index = true

output_dir = "docs"

generate_sitemap = true

theme = "radion"

taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[search]
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
radion_title = "Micah's Secret Blog"
author = "Micah Kepe"
github = "https://github.com/micahkepe"
radion_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]

toc = true

# Nicer codeblocks with copy to clipboard
codeblock = true

# Enable MathJax rendering support
latex = true

# Enable search bar
enable_search = true

# Light/Dark Mode set
theme = "toggle" # options: {light, dark, auto, toggle}

# # Comment sections
comments = true
giscus_repo = "micahkepe/blog"
giscus_repo_id = "R_kgDONfHznQ"
giscus_data_category_id = "DIC_kwDONfHznc4CnQJ4"
